#!/usr/bin/env python3
"""Generate golden references for the ADGENCOV CLI pipeline tests.

Writes a small expression-matrix fixture (tests/fixtures/expr_fixture.tsv) and
then drives the ORIGINAL prototype's load_expression_matrix -> preprocess ->
build_group_labels(gene_family) -> recommend_estimator on it, emitting
tests/golden_pipeline.hpp.  This validates the C++ I/O, preprocessing, group
builder and the end-to-end recommendation against the reference implementation.

Regenerate with:
    .goldenv/bin/python tests/gen_golden_pipeline.py
"""
from __future__ import annotations
import importlib.util
import os
import sys

import numpy as np
import pandas as pd

import adtarget_ref  # shared AD-target reference (same dir on sys.path)

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.join(
    HERE, "..", "..", "uploads", "ad_extracted",
    "ad_covariance_application_note_v3", "ad_covariance_app.py",
)
FIXDIR = os.path.join(HERE, "fixtures")
FIXTURE = os.path.join(FIXDIR, "expr_fixture.tsv")

spec = importlib.util.spec_from_file_location("proto", os.path.abspath(PROTO))
proto = importlib.util.module_from_spec(spec)
sys.modules["proto"] = proto
spec.loader.exec_module(proto)

# ---- Build a deterministic fixture ---------------------------------------
# 6 samples (regex-selectable _LL columns), 10 gene rows including one
# duplicate symbol and one low-mean row that preprocessing should drop.
sample_cols = ["Dex_LL01", "Dex_LL02", "Dex_LL03",
               "Untreated_LL04", "Untreated_LL05", "Untreated_LL06"]
rng = np.random.default_rng(20260704)

rows = [
    ("RPS3",   [120.0, 110.0,  98.0,  60.0,  55.0,  70.0]),
    ("RPL7",   [ 80.0,  92.0,  85.0,  40.0,  38.0,  47.0]),
    ("COL1A1", [  5.0,   6.0,   4.0,  55.0,  60.0,  48.0]),
    ("HIST1H", [ 30.0,  28.0,  33.0,  12.0,  10.0,  15.0]),
    ("KRT8",   [ 12.0,  15.0,  11.0,  40.0,  44.0,  36.0]),
    ("ACTB",   [200.0, 210.0, 190.0, 205.0, 215.0, 198.0]),  # high mean, low var
    ("TP53",   [  9.0,   4.0,  14.0,   3.0,  18.0,   7.0]),
    ("MIR21",  [  2.0,   3.0,   2.5,   1.0,   1.5,   2.0]),
    ("RPS3",   [ 10.0,  11.0,   9.0,   8.0,   7.0,  12.0]),  # duplicate, lower mean
    ("GHOST",  [0.001, 0.0,   0.002, 0.0,   0.001, 0.0]),    # below min_mean -> dropped
]
df = pd.DataFrame([[g] + list(v) for g, v in rows],
                  columns=["gene_short_name"] + sample_cols)
os.makedirs(FIXDIR, exist_ok=True)
df.to_csv(FIXTURE, sep="\t", index=False)

# ---- Drive the prototype -------------------------------------------------
N_GENES = 6
MIN_MEAN = 0.1
loaded = proto.load_expression_matrix(FIXTURE, r"_LL[0-9]+", "gene_short_name")
ds = proto.preprocess(loaded, n_genes=N_GENES, min_mean=MIN_MEAN)
labels = proto.build_group_labels(ds, "gene_family")
# Extended grid (prototype grid + AD-target family), mirroring candidate_grid().
# rows: [sig, method, params, loo_nll, condition_number], ascending by loo_nll.
results = adtarget_ref.ranked(proto, ds.X, labels)

genes = ds.genes
X = ds.X  # samples x genes, standardized
best_method = results[0][1]
best_loo = results[0][3]


def fmt(x: float) -> str:
    return repr(float(x))


lines = []
lines.append("// AUTO-GENERATED by tests/gen_golden_pipeline.py — do not edit.")
lines.append("#pragma once")
lines.append("#include <string>")
lines.append("#include <vector>")
lines.append("namespace golden_pipeline {")
lines.append(f"inline constexpr int kNSamples = {X.shape[0]};")
lines.append(f"inline constexpr int kNGenes = {X.shape[1]};")
lines.append("inline const std::vector<std::string> kGenes = {" +
             ", ".join(f"\"{g}\"" for g in genes) + "};")
lines.append("inline const std::vector<std::string> kLabels = {" +
             ", ".join(f"\"{l}\"" for l in labels) + "};")
# standardized X, row-major
flatX = ", ".join(fmt(v) for v in X.flatten(order="C"))
lines.append("inline const std::vector<double> kX = {" + flatX + "};")
lines.append(f"inline const std::string kBestMethod = \"{best_method}\";")
lines.append(f"inline constexpr double kBestLooNll = {fmt(best_loo)};")
# Full ranking for a stronger check.
lines.append("inline const std::vector<std::string> kRankMethods = {" +
             ", ".join(f"\"{row[1]}\"" for row in results) + "};")
lines.append("inline const std::vector<double> kRankLooNll = {" +
             ", ".join(fmt(row[3]) for row in results) + "};")
lines.append("}  // namespace golden_pipeline")

OUT = os.path.join(HERE, "golden_pipeline.hpp")
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {FIXTURE}")
print(f"Wrote {OUT}")
print(f"selected genes: {genes}")
print(f"labels: {labels}")
print(f"best: {best_method} loo_nll={best_loo:.6f}")
