#!/usr/bin/env python3
"""Generate golden references for the ADGENCOV clustering / data-driven groups.

Drives the ORIGINAL prototype's build_group_labels for the two clustering-based
partitions (correlation_blocks, hierarchical_wreath) on the shared expression
fixture, and also runs sklearn's AgglomerativeClustering on a fixed precomputed
distance matrix.  Emits tests/golden_clustering.hpp so the C++ average-linkage
implementation is checked partition-for-partition against sklearn.

Regenerate with:
    .goldenv/bin/python tests/gen_golden_clustering.py
"""
from __future__ import annotations
import importlib.util
import os
import sys

import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.join(
    HERE, "..", "..", "uploads", "ad_extracted",
    "ad_covariance_application_note_v3", "ad_covariance_app.py",
)
FIXDIR = os.path.join(HERE, "fixtures")
FIXTURE = os.path.join(FIXDIR, "expr_fixture.tsv")
GROUPMAP = os.path.join(FIXDIR, "group_map_fixture.tsv")

spec = importlib.util.spec_from_file_location("proto", os.path.abspath(PROTO))
proto = importlib.util.module_from_spec(spec)
sys.modules["proto"] = proto
spec.loader.exec_module(proto)

# ---- Same preprocessing path as the pipeline golden ----------------------
N_GENES = 6
MIN_MEAN = 0.1
N_BLOCKS = 4
loaded = proto.load_expression_matrix(FIXTURE, r"_LL[0-9]+", "gene_short_name")
ds = proto.preprocess(loaded, n_genes=N_GENES, min_mean=MIN_MEAN)
genes = list(ds.genes)

# correlation_blocks straight from the prototype (uses sklearn under the hood).
cb_labels = proto.build_group_labels(ds, "correlation_blocks", n_blocks=N_BLOCKS)

# A deterministic coarse group map over the selected genes for the wreath:
# split the selected genes into two coarse groups by index parity.  Written to
# a fixture so the C++ CLI/test consumes the identical mapping.
gm = pd.DataFrame({
    "gene": genes,
    "group": ["G0" if i % 2 == 0 else "G1" for i in range(len(genes))],
})
os.makedirs(FIXDIR, exist_ok=True)
gm.to_csv(GROUPMAP, sep="\t", index=False)
hw_labels = proto.build_group_labels(
    ds, "hierarchical_wreath", n_blocks=N_BLOCKS, group_map=gm)

# ---- Standalone precomputed-distance clustering vs sklearn ----------------
# Two tight pairs {0,1}, {2,3} and a loner {4}.
Dmat = np.array([
    [0.00, 0.10, 0.80, 0.90, 0.50],
    [0.10, 0.00, 0.85, 0.88, 0.55],
    [0.80, 0.85, 0.00, 0.15, 0.60],
    [0.90, 0.88, 0.15, 0.00, 0.65],
    [0.50, 0.55, 0.60, 0.65, 0.00],
], dtype=float)
try:
    sk = AgglomerativeClustering(n_clusters=3, metric="precomputed", linkage="average")
except TypeError:
    sk = AgglomerativeClustering(n_clusters=3, affinity="precomputed", linkage="average")
sk_labels = [int(x) for x in sk.fit_predict(Dmat)]


def vec_str(name, vals):
    return (f"inline const std::vector<std::string> {name} = {{" +
            ", ".join(f"\"{v}\"" for v in vals) + "};")


lines = []
lines.append("// AUTO-GENERATED by tests/gen_golden_clustering.py — do not edit.")
lines.append("#pragma once")
lines.append("#include <string>")
lines.append("#include <vector>")
lines.append("namespace golden_clustering {")
lines.append(f"inline constexpr int kNBlocks = {N_BLOCKS};")
lines.append(vec_str("kGenes", genes))
lines.append(vec_str("kCorrBlocks", cb_labels))
lines.append(vec_str("kWreath", hw_labels))
# Standalone distance matrix (row-major) + sklearn's partition.
flatD = ", ".join(repr(float(v)) for v in Dmat.flatten(order="C"))
lines.append(f"inline constexpr int kDdim = {Dmat.shape[0]};")
lines.append(f"inline constexpr int kDnClusters = 3;")
lines.append("inline const std::vector<double> kD = {" + flatD + "};")
lines.append("inline const std::vector<int> kDLabels = {" +
             ", ".join(str(x) for x in sk_labels) + "};")
lines.append("}  // namespace golden_clustering")

OUT = os.path.join(HERE, "golden_clustering.hpp")
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {GROUPMAP}")
print(f"Wrote {OUT}")
print(f"genes: {genes}")
print(f"correlation_blocks: {cb_labels}")
print(f"hierarchical_wreath: {hw_labels}")
print(f"sklearn standalone labels: {sk_labels}")
