#!/usr/bin/env python3
"""Generate golden reference values for the ADGENCOV estimator unit tests.

We import the ORIGINAL prototype (ad_covariance_app.py) so the C++ port is
validated against the exact numerics the Applications Note describes, plus
scikit-learn's LedoitWolf / OAS for the data-driven shrinkage intensities.

Outputs a C++ header (tests/golden_shrink.hpp) with fixed inputs and expected
outputs as row-major flattened arrays.  Regenerate with:
    .goldenv/bin/python tests/gen_golden.py
"""
from __future__ import annotations
import importlib.util
import os
import sys
import textwrap

import numpy as np
from sklearn.covariance import LedoitWolf, OAS

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.join(
    HERE, "..", "..", "uploads", "ad_extracted",
    "ad_covariance_application_note_v3", "ad_covariance_app.py",
)

spec = importlib.util.spec_from_file_location("proto", os.path.abspath(PROTO))
proto = importlib.util.module_from_spec(spec)
sys.modules["proto"] = proto          # needed so @dataclass can resolve __module__
spec.loader.exec_module(proto)

# ---------------------------------------------------------------------------
# Fixed test fixture: n=6 samples, p=5 genes.  Column-correlated on purpose so
# the covariance has meaningful off-diagonal structure.  Values are exact
# decimal literals so the C++ side uses byte-identical inputs.
# ---------------------------------------------------------------------------
X = np.array([
    [ 1.20, -0.30,  2.10,  0.05, -1.10],
    [ 0.40,  0.90, -0.60,  1.30,  0.70],
    [-1.50,  0.20,  0.80, -0.40,  1.60],
    [ 2.30, -1.10,  1.40,  0.90, -0.50],
    [-0.70,  1.50, -1.20, -1.00,  2.20],
    [ 0.60,  0.10,  0.30, -0.20, -0.90],
], dtype=float)
n, p = X.shape
labels = [0, 0, 1, 1, 1]          # two blocks: sizes 2 and 3

S       = proto.sample_covariance(X)                 # ddof=1
S_proj  = proto.ad_project_covariance(S, labels)     # Reynolds projection of S
make_pd = proto.make_pd

# Deterministic estimator suite ------------------------------------------------
RIDGE_ALPHAS = [0.05, 0.2, 0.7]
LAM          = 0.10
L1_RATIO_EN  = 0.25

# scikit-learn data-driven shrinkage
lw = LedoitWolf().fit(X)
oas = OAS().fit(X)
lw_shrink = float(lw.shrinkage_)
oas_shrink = float(oas.shrinkage_)

cases = {}  # name -> matrix

cases["sample_cov"]       = S
cases["reynolds_of_cov"]  = S_proj
cases["make_pd_of_cov"]   = make_pd(S)

for a in RIDGE_ALPHAS:
    tag = str(a).replace('.', 'p')
    cases[f"ridge_{tag}"]    = proto.ridge(S, a)
    cases[f"ad_ridge_{tag}"] = proto.ridge(S_proj, a)

cases["lasso"]              = proto.soft_threshold_offdiag(S, LAM, 1.0)
cases["ad_lasso"]           = proto.soft_threshold_offdiag(S_proj, LAM, 1.0)
cases["elastic_net"]        = proto.soft_threshold_offdiag(S, LAM, L1_RATIO_EN)
cases["ad_elastic_net"]     = proto.soft_threshold_offdiag(S_proj, LAM, L1_RATIO_EN)

cases["ledoit_wolf_cov"]    = np.asarray(lw.covariance_)
cases["oas_cov"]            = np.asarray(oas.covariance_)
cases["ad_linear_lw"]       = proto.ridge(S_proj, lw_shrink)
cases["ad_oas"]             = proto.ridge(S_proj, oas_shrink)

# Full make_pd'd estimator outputs (what estimate_covariance actually returns)
cases["make_pd_ad_ridge_0p2"] = make_pd(proto.ridge(S_proj, 0.2))
cases["make_pd_ad_lasso"]     = make_pd(proto.soft_threshold_offdiag(S_proj, LAM, 1.0))

# ---------------------------------------------------------------------------
# Emit C++ header
# ---------------------------------------------------------------------------
def fmt_mat(name, M):
    M = np.asarray(M, dtype=float)
    r, c = M.shape
    flat = ", ".join(f"{v:.17g}" for v in M.flatten(order="C"))
    return (f"inline const GoldenMat {name} {{\n"
            f"    {r}, {c},\n"
            f"    {{{flat}}}\n}};\n")

lines = []
lines.append("// AUTO-GENERATED by tests/gen_golden.py — do not edit by hand.")
lines.append("// Reference values from the prototype ad_covariance_app.py + scikit-learn.")
lines.append("#ifndef ADGENCOV_GOLDEN_SHRINK_HPP")
lines.append("#define ADGENCOV_GOLDEN_SHRINK_HPP")
lines.append("#include <vector>")
lines.append("")
lines.append("namespace golden {")
lines.append("")
lines.append("struct GoldenMat { int rows; int cols; std::vector<double> data; };")
lines.append("")
lines.append(f"inline const int kN = {n};")
lines.append(f"inline const int kP = {p};")
Xflat = ", ".join(f"{v:.17g}" for v in X.flatten(order="C"))
lines.append(f"inline const std::vector<double> kX {{{Xflat}}};  // {n}x{p} row-major")
lines.append(f"inline const std::vector<int> kLabels {{{', '.join(str(l) for l in labels)}}};")
lines.append(f"inline const double kLwShrink = {lw_shrink:.17g};")
lines.append(f"inline const double kOasShrink = {oas_shrink:.17g};")
lines.append(f"inline const double kLam = {LAM:.17g};")
lines.append(f"inline const double kL1RatioEn = {L1_RATIO_EN:.17g};")
lines.append("")
for name, M in cases.items():
    lines.append(fmt_mat(name, M))
lines.append("}  // namespace golden")
lines.append("")
lines.append("#endif  // ADGENCOV_GOLDEN_SHRINK_HPP")

out = os.path.join(HERE, "golden_shrink.hpp")
with open(out, "w") as f:
    f.write("\n".join(lines))
print(f"Wrote {out}")
print(f"  LedoitWolf shrinkage = {lw_shrink:.6f}")
print(f"  OAS shrinkage        = {oas_shrink:.6f}")
print(f"  {len(cases)} golden matrices")
