// AUTO-GENERATED by tests/gen_golden_clustering.py — do not edit.
#pragma once
#include <string>
#include <vector>
namespace golden_clustering {
inline constexpr int kNBlocks = 4;
inline const std::vector<std::string> kGenes = {"COL1A1", "KRT8", "TP53", "HIST1H", "RPL7", "RPS3"};
inline const std::vector<std::string> kCorrBlocks = {"block_0", "block_0", "block_3", "block_0", "block_1", "block_2"};
inline const std::vector<std::string> kWreath = {"G0::block_0", "G1::block_0", "G0::block_3", "G1::block_0", "G0::block_1", "G1::block_2"};
inline constexpr int kDdim = 5;
inline constexpr int kDnClusters = 3;
inline const std::vector<double> kD = {0.0, 0.1, 0.8, 0.9, 0.5, 0.1, 0.0, 0.85, 0.88, 0.55, 0.8, 0.85, 0.0, 0.15, 0.6, 0.9, 0.88, 0.15, 0.0, 0.65, 0.5, 0.55, 0.6, 0.65, 0.0};
inline const std::vector<int> kDLabels = {1, 1, 0, 0, 2};
}  // namespace golden_clustering
