// Estimator-family unit tests for ADGENCOV.
//
// Every linear/sparse estimator and every Ledoit-Wolf / OAS intensity is
// validated against golden values generated by tests/gen_golden.py from the
// ORIGINAL prototype (ad_covariance_app.py) and scikit-learn.  The AD variants
// are checked by composing reynolds_project with the corresponding estimator,
// exactly as the Applications Note's estimate_covariance does.
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <vector>
#include <Eigen/Dense>

#include "adgencov/projection.hpp"
#include "adgencov/shrink.hpp"
#include "golden_shrink.hpp"

using Catch::Matchers::WithinAbs;
using namespace adgencov;

namespace {

// Golden values are printed with full double precision; agreement to ~1e-9 is a
// tight validation of the ported numerics against NumPy / scikit-learn.
constexpr double kTol = 1e-9;

// Rebuild the fixed test fixture X (n x p, row-major) from the golden header.
Eigen::MatrixXd fixtureX() {
  Eigen::MatrixXd X(golden::kN, golden::kP);
  for (int i = 0; i < golden::kN; ++i)
    for (int j = 0; j < golden::kP; ++j)
      X(i, j) = golden::kX[static_cast<std::size_t>(i) * golden::kP + j];
  return X;
}

std::vector<int> fixtureLabels() { return golden::kLabels; }

Eigen::MatrixXd toEigen(const golden::GoldenMat& g) {
  Eigen::MatrixXd M(g.rows, g.cols);
  for (int i = 0; i < g.rows; ++i)
    for (int j = 0; j < g.cols; ++j)
      M(i, j) = g.data[static_cast<std::size_t>(i) * g.cols + j];
  return M;
}

// Assert two matrices agree entrywise to within kTol.
void expectClose(const Eigen::MatrixXd& got, const golden::GoldenMat& want,
                 double tol = kTol) {
  const Eigen::MatrixXd expected = toEigen(want);
  REQUIRE(got.rows() == expected.rows());
  REQUIRE(got.cols() == expected.cols());
  const double err = (got - expected).cwiseAbs().maxCoeff();
  INFO("max abs entrywise error = " << err);
  REQUIRE(err <= tol);
}

bool isSymmetric(const Eigen::MatrixXd& M, double tol = 1e-12) {
  return (M - M.transpose()).cwiseAbs().maxCoeff() <= tol;
}

bool isSPD(const Eigen::MatrixXd& M, double floor = 1e-9) {
  Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> es(M);
  return es.info() == Eigen::Success && es.eigenvalues().minCoeff() >= floor;
}

}  // namespace

// --- Building blocks ---------------------------------------------------------

TEST_CASE("sample_covariance matches numpy.cov (ddof=1)", "[shrink][sample]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  expectClose(S, golden::sample_cov);
  REQUIRE(isSymmetric(S));
}

TEST_CASE("sample_covariance biased divides by n", "[shrink][sample]") {
  const Eigen::MatrixXd X = fixtureX();
  const Eigen::MatrixXd unbiased = sample_covariance(X, true);
  const Eigen::MatrixXd biased = sample_covariance(X, false);
  const double ratio = static_cast<double>(X.rows() - 1) / X.rows();
  // biased = (n-1)/n * unbiased.
  REQUIRE((biased - ratio * unbiased).cwiseAbs().maxCoeff() <= kTol);
}

TEST_CASE("sample_covariance rejects degenerate input", "[shrink][sample]") {
  Eigen::MatrixXd one(1, 3);
  one << 1.0, 2.0, 3.0;
  REQUIRE_THROWS(sample_covariance(one, /*unbiased=*/true));
}

TEST_CASE("make_pd matches reference and yields an SPD matrix", "[shrink][pd]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd P = make_pd(S);
  expectClose(P, golden::make_pd_of_cov);
  REQUIRE(isSymmetric(P));
  REQUIRE(isSPD(P, 1e-6));  // eigenvalues floored at 1e-5 by default
}

TEST_CASE("make_pd floors negative eigenvalues, keeps large ones",
          "[shrink][pd]") {
  Eigen::MatrixXd S(2, 2);
  S << 1.0, 2.0,
       2.0, 1.0;  // eigenvalues 3 and -1
  const Eigen::MatrixXd P = make_pd(S, 1e-3);
  Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> es(P);
  const Eigen::VectorXd ev = es.eigenvalues();  // ascending
  REQUIRE_THAT(ev(0), WithinAbs(1e-3, 1e-9));
  REQUIRE_THAT(ev(1), WithinAbs(3.0, 1e-9));
}

// --- Ridge -------------------------------------------------------------------

TEST_CASE("ridge matches reference across intensities", "[shrink][ridge]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  expectClose(ridge(S, 0.05), golden::ridge_0p05);
  expectClose(ridge(S, 0.2), golden::ridge_0p2);
  expectClose(ridge(S, 0.7), golden::ridge_0p7);
}

TEST_CASE("ridge endpoints behave", "[shrink][ridge]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  // alpha=0 is the identity map on S.
  REQUIRE((ridge(S, 0.0) - S).cwiseAbs().maxCoeff() <= kTol);
  // alpha=1 collapses to mu*I.
  const double mu = S.trace() / S.rows();
  const Eigen::MatrixXd target = mu * Eigen::MatrixXd::Identity(S.rows(), S.cols());
  REQUIRE((ridge(S, 1.0) - target).cwiseAbs().maxCoeff() <= kTol);
}

// --- Sparse (LASSO / elastic-net) --------------------------------------------

TEST_CASE("soft_threshold LASSO matches reference", "[shrink][sparse]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  expectClose(soft_threshold_offdiag(S, golden::kLam, 1.0), golden::lasso);
}

TEST_CASE("soft_threshold elastic-net matches reference", "[shrink][sparse]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  expectClose(soft_threshold_offdiag(S, golden::kLam, golden::kL1RatioEn),
              golden::elastic_net);
}

TEST_CASE("soft_threshold preserves diagonal under pure LASSO",
          "[shrink][sparse]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd R = soft_threshold_offdiag(S, golden::kLam, 1.0);
  REQUIRE((R.diagonal() - S.diagonal()).cwiseAbs().maxCoeff() <= kTol);
}

TEST_CASE("large lambda zeros the off-diagonal", "[shrink][sparse]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd R = soft_threshold_offdiag(S, 1e6, 1.0);
  Eigen::MatrixXd offdiag = R;
  offdiag.diagonal().setZero();
  REQUIRE(offdiag.cwiseAbs().maxCoeff() <= kTol);
}

// --- Ledoit-Wolf -------------------------------------------------------------

TEST_CASE("Ledoit-Wolf shrinkage matches scikit-learn", "[shrink][lw]") {
  const double d = ledoit_wolf_shrinkage(fixtureX());
  INFO("got shrinkage = " << d << ", want = " << golden::kLwShrink);
  REQUIRE_THAT(d, WithinAbs(golden::kLwShrink, kTol));
}

TEST_CASE("Ledoit-Wolf covariance matches scikit-learn", "[shrink][lw]") {
  const Eigen::MatrixXd C = ledoit_wolf(fixtureX());
  expectClose(C, golden::ledoit_wolf_cov);
  REQUIRE(isSymmetric(C));
}

// --- OAS ---------------------------------------------------------------------

TEST_CASE("OAS shrinkage matches scikit-learn", "[shrink][oas]") {
  const double d = oas_shrinkage(fixtureX());
  INFO("got shrinkage = " << d << ", want = " << golden::kOasShrink);
  REQUIRE_THAT(d, WithinAbs(golden::kOasShrink, kTol));
}

TEST_CASE("OAS covariance matches scikit-learn", "[shrink][oas]") {
  const Eigen::MatrixXd C = oas(fixtureX());
  expectClose(C, golden::oas_cov);
  REQUIRE(isSymmetric(C));
}

// --- Algebraic-Diversity variants (project, then estimate) -------------------
// These are the headline claims of the Note: each AD estimator must equal the
// linear estimator applied to the Reynolds-projected sample covariance.

TEST_CASE("Reynolds projection of the sample covariance matches reference",
          "[shrink][ad]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd Sproj = reynolds_project(S, fixtureLabels());
  expectClose(Sproj, golden::reynolds_of_cov);
}

TEST_CASE("ad_ridge = ridge(reynolds(S)) across intensities", "[shrink][ad]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd Sproj = reynolds_project(S, fixtureLabels());
  expectClose(ridge(Sproj, 0.05), golden::ad_ridge_0p05);
  expectClose(ridge(Sproj, 0.2), golden::ad_ridge_0p2);
  expectClose(ridge(Sproj, 0.7), golden::ad_ridge_0p7);
}

TEST_CASE("ad_lasso = soft_threshold(reynolds(S))", "[shrink][ad]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd Sproj = reynolds_project(S, fixtureLabels());
  expectClose(soft_threshold_offdiag(Sproj, golden::kLam, 1.0), golden::ad_lasso);
}

TEST_CASE("ad_elastic_net = soft_threshold(reynolds(S))", "[shrink][ad]") {
  const Eigen::MatrixXd S = sample_covariance(fixtureX());
  const Eigen::MatrixXd Sproj = reynolds_project(S, fixtureLabels());
  expectClose(soft_threshold_offdiag(Sproj, golden::kLam, golden::kL1RatioEn),
              golden::ad_elastic_net);
}

TEST_CASE("ad_linear_lw = ridge(reynolds(S), lw_shrinkage(X))", "[shrink][ad]") {
  const Eigen::MatrixXd X = fixtureX();
  const Eigen::MatrixXd Sproj = reynolds_project(sample_covariance(X),
                                                 fixtureLabels());
  const double d = ledoit_wolf_shrinkage(X);
  expectClose(ridge(Sproj, d), golden::ad_linear_lw);
}

TEST_CASE("ad_oas = ridge(reynolds(S), oas_shrinkage(X))", "[shrink][ad]") {
  const Eigen::MatrixXd X = fixtureX();
  const Eigen::MatrixXd Sproj = reynolds_project(sample_covariance(X),
                                                 fixtureLabels());
  const double d = oas_shrinkage(X);
  expectClose(ridge(Sproj, d), golden::ad_oas);
}

// --- Full estimator outputs (make_pd wrapper) --------------------------------

TEST_CASE("make_pd(ad_ridge) matches the estimate_covariance output",
          "[shrink][ad]") {
  const Eigen::MatrixXd Sproj =
      reynolds_project(sample_covariance(fixtureX()), fixtureLabels());
  expectClose(make_pd(ridge(Sproj, 0.2)), golden::make_pd_ad_ridge_0p2);
}

TEST_CASE("make_pd(ad_lasso) matches the estimate_covariance output",
          "[shrink][ad]") {
  const Eigen::MatrixXd Sproj =
      reynolds_project(sample_covariance(fixtureX()), fixtureLabels());
  expectClose(make_pd(soft_threshold_offdiag(Sproj, golden::kLam, 1.0)),
              golden::make_pd_ad_lasso);
}
